-- ==============================================================================
-- SCHEMA DO SUPABASE: Tabela de Confirmações de Presença
-- Executar este script no SQL Editor do painel do Supabase
-- ==============================================================================

-- 1. Criação da tabela confirmacoes
create table if not exists public.confirmacoes (
    id bigint generated by default as identity primary key,
    convite text not null,
    nome text not null,
    acompanhantes text default 'Não possui',
    presenca boolean not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitação de Segurança por Nível de Linha (RLS)
alter table public.confirmacoes enable row level security;

-- 3. Políticas de Acesso (Least Privilege):
-- 3.1. Convidado pode APENAS inserir sua resposta (INSERT liberado para anon e authenticated)
drop policy if exists "Permitir insercao publica de confirmacoes" on public.confirmacoes;
create policy "Permitir insercao publica de confirmacoes"
on public.confirmacoes
for insert
to anon, authenticated
with check (true);

-- 3.2. Leitura permitida para organizadores autenticados via Supabase Auth ou service_role
-- Convidado público não tem permissão de SELECT sobre a tabela inteira
drop policy if exists "Permitir leitura para organizador autenticado" on public.confirmacoes;
create policy "Permitir leitura para organizador autenticado"
on public.confirmacoes
for select
to authenticated
using (true);

-- 4. Índices para performance
create index if not exists idx_confirmacoes_convite on public.confirmacoes(convite);
create index if not exists idx_confirmacoes_created_at on public.confirmacoes(created_at desc);
